image: node:14.15.0-alpine

.rules-default:
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE == "push" && $CI_OPEN_MERGE_REQUESTS' # When there's an open merge request, don't run the job on pushes
      when: never
    - when: always # Otherwise always run the job

stages:
  - lint
  - build
  - test
  - deploy

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

before_script:
  - yarn install --frozen-lockfile

lint:
  extends: .rules-default
  stage: lint
  needs: []
  script:
    - yarn lint
    - yarn type-check

jest-tests:
  extends: .rules-default
  stage: test
  needs: []
  script:
    - yarn jest --coverage --ci
  artifacts:
    reports:
      cobertura: coverage/cobertura-coverage.xml

build-image:
  stage: build
  needs: []
  image: docker:stable
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

e2e-tests:
  stage: test
  needs: ['build-image']
  image: cypress/base:14.15.0
  variables:
    HTTPS: 'true' # Use HTTPS for backend
    FRONTEND_SERVICE_URL: https://expo:19006
    BACKEND_SERVICE_URL: https://backend:3000
    #EXPO_FIREBASE_CLIENT_ID: $EXPO_FIREBASE_CLIENT_ID # Redundant due to hardcoded value
    EXPO_SERVER: $BACKEND_SERVICE_URL
    CYPRESS_BASE_URL: $FRONTEND_SERVICE_URL
    CYPRESS_BACKEND_URL: $BACKEND_SERVICE_URL
  services:
    - name: ${CI_REGISTRY}/aalto/pakettikauppa-backend:master
      alias: backend
    - name: $CONTAINER_TEST_IMAGE
      alias: expo
  script:
    - $(npm bin)/cypress run
  artifacts:
    when: on_failure
    paths:
      - cypress/videos
      - cypress/screenshots
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

expo-deployments:
  stage: deploy
  environment:
    name: production-expo
    url: https://expo.io/@pakettikauppa/projects/pakettikauppa-expo
  script:
    - yarn global add expo-cli
    - yarn expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - yarn expo publish --non-interactive
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

netlify-deployment:
  stage: deploy
  environment:
    name: production-netlify
    url: https://pakettikauppa-expo.netlify.app
  script:
    - yarn global add expo-cli
    - yarn global add netlify-cli
    - yarn expo build:web
    - echo "/*    /index.html   200" > web-build/_redirects
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
