variables:
  GIT_CLEAN_FLAGS: -ffdx -e .yarn -e .jest -e node_modules/

image: node:14.15.0-alpine

stages:
  - lint
  - test
  - deploy

before_script:
  - yarn install --cache-folder .yarn --frozen-lockfile
  - echo EXPO_FIREBASE_CLIENT_ID=$EXPO_FIREBASE_CLIENT_ID > .env
  - echo EXPO_SERVER=$EXPO_SERVER >> .env

lint:
  stage: lint
  needs: []
  script:
    - yarn lint
    - yarn type-check

jest-tests:
  stage: test
  needs: []
  script:
    - yarn jest --coverage --ci --cacheDirectory .jest
  artifacts:
    reports:
      cobertura: coverage/cobertura-coverage.xml

expo-deployments:
  stage: deploy
  script:
    - yarn global add expo-cli --cache-folder .yarn
    - yarn expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - yarn expo publish --non-interactive
  only:
    - master

netlify-deployment:
  stage: deploy
  script:
    - yarn global add expo-cli --cache-folder .yarn
    - yarn global add netlify-cli --cache-folder .yarn
    - yarn expo build:web
    - echo "/*    /index.html   200" > web-build/_redirects
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  only:
    - master
