image: node:14.15.0-alpine
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ~/.npm
    - .jest
    - node_modules/
stages:
  - test
  - deploy-expo
  - deploy-netlify
before_script:
  - yarn install --frozen-lockfile
jest-tests:
  stage: test
  script:
    - yarn jest --ci
expo-deployments:
  stage: deploy-expo
  script:
    - yarn expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - yarn expo publish --non-interactive
netlify-deployment:
  stage: deploy-netlify
  script:
    - yarn global add netlify-cli
    - yarn expo build:web
    - echo "/*    /index.html   200" > web-build/_redirects
    - yarn netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
