image: node:14.15.0
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ~/.npm
    - .jest
    - node_modules/
stages:
  - deploy-expo
before_script:
  - yarn install --frozen-lockfile
  - yarn global add expo-cli
#jest-tests:
#  stage: test
#  script:
    #- yarn run jest --ci
#netlify-deployment:
#  stage: deploy-netlify
#  script:
#    - yarn add netlify-cli
#    - yarn global add expo-cli
#    - yarn expo build:web
    #- yarn netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
expo-deployments:
  stage: deploy-expo
  script:
    - yarn run expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - yarn run expo publish --non-interactive
