import { Shipment } from '../../../types'

export const mockShipmentData: Shipment[] = [
  {
    id: 1,
    createdOn: new Date(2021, 0, 4),
    receiverName: 'Henry',
    receiverEmail: 'henry@posti.fi',
    postCode: '02150',
    postOffice: 'Espoo',
    countryCode: 'FI',
    price: 42,
    status: '',
    reference: '',
    latestEvent: '',
    deliveryCompany: 'Posti',
    invoiceNumber: '',
  },
  {
    id: 2,
    createdOn: new Date(2020, 11, 25),
    receiverName: 'Joose',
    receiverEmail: 'joose@posti.fi',
    postCode: '01530',
    postOffice: 'Vantaa',
    countryCode: 'FI',
    price: 25,
    status: '',
    reference: '',
    latestEvent: '',
    deliveryCompany: 'Posti',
    invoiceNumber: '',
  },
  {
    id: 3,
    createdOn: new Date(2020, 11, 25),
    receiverName: 'Testeri',
    receiverEmail: 'testeri@posti.fi',
    postCode: '02700',
    postOffice: 'Kauniainen',
    countryCode: 'FI',
    price: 25,
    status: '',
    reference: '',
    latestEvent: '',
    deliveryCompany: 'Posti',
    invoiceNumber: '',
  },
]