import { Shipment } from '../../../../types'

export const mockShipmentData: Shipment[] = [
  {
    id: 1,
    createdOn: '1/1/2021',
    receiverName: 'Henry',
    receiverEmail: 'henry@posti.fi',
    receiverPostCode: '02150',
    receiverCity: 'Espoo',
    receiverCountry: 'Finland',
    price: 42,
    status: '',
    reference: '',
    latestEvent: '',
    deliveryCompany: 'Posti',
    invoiceNumber: '',
    shippingMethod: 'Noutopistepaketti',
  },
  {
    id: 2,
    createdOn: '',
    receiverName: 'Joose',
    receiverEmail: 'joose@posti.fi',
    receiverPostCode: '02150',
    receiverCity: 'Espoo',
    receiverCountry: 'Finland',
    price: 25,
    status: '',
    reference: '',
    latestEvent: '',
    deliveryCompany: 'Posti',
    invoiceNumber: '',
    shippingMethod: 'Noutopistepaketti',
  },
  {
    id: 3,
    createdOn: '',
    receiverName: 'Testeri',
    receiverEmail: 'testeri@posti.fi',
    receiverPostCode: '02150',
    receiverCity: 'Espoo',
    receiverCountry: 'Finland',
    price: 25,
    status: '',
    reference: '',
    latestEvent: '',
    deliveryCompany: 'Posti',
    invoiceNumber: '',
    shippingMethod: 'Noutopistepaketti',
  },
]
