import { Shipment } from '../../../../types'

export const mockShipmentData: Shipment[] = [
  {
    id: 1,
    createdOn: '1/1/2021',
    receiverName: 'Henry',
    receiverEmail: 'henry@posti.fi',
    postCode: '02150',
    postOffice: 'Espoo',
    countryCode: 'FI',
    price: 42,
    status: '',
    reference: '',
    latestEvent: '',
    deliveryCompany: 'Posti',
    invoiceNumber: '',
    shippingMethod: 'Noutopistepaketti',
  },
  {
    id: 2,
    createdOn: '',
    receiverName: 'Joose',
    receiverEmail: 'joose@posti.fi',
    postCode: '01530',
    postOffice: 'Vantaa',
    countryCode: 'FI',
    price: 25,
    status: '',
    reference: '',
    latestEvent: '',
    deliveryCompany: 'Posti',
    invoiceNumber: '',
    shippingMethod: 'Noutopistepaketti',
  },
  {
    id: 3,
    createdOn: '',
    receiverName: 'Testeri',
    receiverEmail: 'testeri@posti.fi',
    postCode: '02700',
    postOffice: 'Kauniainen',
    countryCode: 'FI',
    price: 25,
    status: '',
    reference: '',
    latestEvent: '',
    deliveryCompany: 'Posti',
    invoiceNumber: '',
    shippingMethod: 'Noutopistepaketti',
  },
]
